// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl4NprHEg8a8BCzsQjD6FBBOTfCCakpDM',
    appId: '1:267248310658:android:cf9c5bd47100e025fe579b',
    messagingSenderId: '267248310658',
    projectId: 'rumo-492120',
    storageBucket: 'rumo-492120.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLwj66M0LTOXsDYQsfktF7W7iyriDU2XA',
    appId: '1:267248310658:ios:95642c767a8a058efe579b',
    messagingSenderId: '267248310658',
    projectId: 'rumo-492120',
    storageBucket: 'rumo-492120.firebasestorage.app',
    iosBundleId: 'com.reniuslab.runnin',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiZdh-xXd9tLZz8OSdxQYIGNjEwu_UqjA',
    appId: '1:267248310658:web:ec2b81abb2a55aacfe579b',
    messagingSenderId: '267248310658',
    projectId: 'rumo-492120',
    authDomain: 'rumo-492120.firebaseapp.com',
    storageBucket: 'rumo-492120.firebasestorage.app',
  );

}