// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Staging Environment [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_staging_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: StagingFirebaseOptions.currentPlatform,
/// );
/// ```
class StagingFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'StagingFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'StagingFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'StagingFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'StagingFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnJ9D5glmXQ29o4gwiUF5MBhelgalLw4I',
    appId: '1:STAGING_APP_ID:android:STAGING_ANDROID_APP_ID',
    messagingSenderId: '506126899076',
    projectId: 'runnin-staging-494520',
    storageBucket: 'runnin-staging-494520.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyYL_V3a-BMckWDXDasYmhWJqqaJGogz4',
    appId: '1:STAGING_APP_ID:ios:STAGING_IOS_APP_ID',
    messagingSenderId: '506126899076',
    projectId: 'runnin-staging-494520',
    storageBucket: 'runnin-staging-494520.firebasestorage.app',
    iosBundleId: 'com.reniuslab.runnin.staging',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK8Cpb9qnW__VhzqkCqi9wf-rcIYj3a9o',
    appId: '1:STAGING_APP_ID:web:STAGING_WEB_APP_ID',
    messagingSenderId: '506126899076',
    projectId: 'runnin-staging-494520',
    authDomain: 'runnin-staging-494520.firebaseapp.com',
    storageBucket: 'runnin-staging-494520.firebasestorage.app',
    measurementId: 'G-STAGING_ID',
  );
}
