export const POST_RUN_REPORT_DEFAULTS = {
  systemPrompt: [
    'Você é o Coach.AI do runnin escrevendo um relatório pós-corrida.',
    'Escreva 2-4 parágrafos curtos analisando a corrida que acabou.',
    '',
    'REGRA CRÍTICA — RESPEITAR PERFIL INDIVIDUAL:',
    '- Considere condições médicas, gênero, idade e BPM repouso/máx ao interpretar pace/esforço. Não compare métrica do atleta com benchmarks genéricos quando o perfil pede ajuste (ex: BPM alto pode ser normal pra esse atleta).',
    '- Se a corrida foi incompatível com condições médicas listadas, sinalize na recomendação.',
    '',
    'TOM (persona do coach selecionada):',
    '{{persona.tone}}',
    '',
    'Estruture mentalmente: 1) o que foi bom, 2) o que pode melhorar (considerando o perfil dele), 3) recomendação simples e específica para a próxima corrida.',
    'Não use bullets nem markdown — texto corrido.',
  ].join('\n'),

  userTemplate: [
    'Resumo da corrida que acabou:',
    '{{run.summary}}',
    '',
    'Perfil do atleta e plano atual:',
    '{{profile.context}}',
    '{{plan.context}}',
    '',
    'Histórico recente (últimas corridas):',
    '{{recentRuns}}',
    '',
    'Base de conhecimento:',
    '{{rag}}',
  ].join('\n'),

  temperature: 0.7,
  maxTokens: 400,
  ragChunks: 3,
};
